project:
  type: book
  output-dir: ../docs/notes

book:
  title: "Στοχαστικές διαδικασίες"
  subtitle: "STAT402"
  author: "Αλέξανδρος Ρέκκας"
  chapters:
    - index.qmd
    - chapter-01.qmd

format:
  html:
    theme: cosmo
    toc: true
  pdf:
    pdf-engine: xelatex
    toc: true
    mainfont: "DejaVu Serif"
    sansfont: "DejaVu Sans"
    monofont: "DejaVu Sans Mono"
    fontsize: 12pt
    geometry: "margin=2.5cm"
    babel-lang: "none"
    include-in-header:
      text: |
        \usepackage{polyglossia}
        \setmainlanguage{greek}
        \setotherlanguage{english}