---
title: "Σημειώσεις Στοχαστικών Διαδικασιών"
---

## Βασικές και μη-βασικές καταστάσεις

**Ορισμοί**

- Μια κατάσταση $i$ ονομάζεται προσιτή ή προσβάσιμη από την κατάσταση $j$ αν $\exists n \ge 0 : P_{ij}(n) > 0$. Γράφουμε $j \to i$.
- Δύο καταστάσεις $i$ και $j$ που είναι προσιτές μεταξύ τους βρίσκονται σε επικοινωνία. Γράφουμε $i \leftrightarrow j$.

**Τύποι καταστάσεων**

- Κατάσταση απορρόφησης: Μια κατάσταση $i$ με $P_{ij}(n) = 0, n > 0$ και $i \ne j$.
- Μη βασική κατάσταση: Η κατάσταση $i$ είναι μη βασική αν $\forall j \in S$ με $i \to j \Rightarrow j \not\to i$ ή αν $\exists j \in S$ με $i \to j$. (Σημείωση: τυπικά αν υπάρχει $j$ προσβάσιμη από την $i$ αλλά η $i$ όχι από τη $j$).
- Βασική κατάσταση: Η κατάσταση $i$ είναι βασική αν $\forall j \in S$ με $i \to j \Rightarrow j \to i$.

**Πρόταση**  
(1) Για κάθε $i \in S$ που δεν είναι κατάσταση απορρόφησης, υπάρχει $j \in S$ τέτοια ώστε $i \to j$.  
(2) Αν η $i \in S$ είναι βασική, τότε $i \leftrightarrow i$.  
(3) Αν $i \leftrightarrow j$ και $j \leftrightarrow k$ τότε $i \leftrightarrow k$.  
(4) Αν η $i \in S$ είναι βασική και $\exists j \in S$ με $i \to j$ τότε η $j$ είναι βασική και $i \leftrightarrow j$.

**Απόδειξη**  
(1) Αφού η $i$ δεν είναι κατάσταση απορρόφησης, $\exists j \in S$ με $i \ne j$ και $P_{ij}(n) > 0$. Άρα $i \to j$.
(2) $\cdot$ Αν η $i \in S$ είναι κατάσταση απορρόφησης, τότε είναι προφανές.
$\cdot$ Αν η $i \in S$ δεν είναι κατάσταση απορρόφησης, $\exists j \in S$ με $i \to j$. Αφού $i$ βασική $j \to i$.
$i \to j : \exists n_1 > 0$ τ.ω. $P_{ij}(n_1) > 0$
$j \to i : \exists n_2 > 0$ τ.ω. $P_{ji}(n_2) > 0$

Από θ. Chapman-Kolmogorov:
$$P_{ii}(n_1+n_2) = \sum_{l \in S} P_{il}(n_1) P_{li}(n_2) = P_{ij}(n_1) P_{ji}(n_2) + \sum_{l \ne j} P_{il}(n_1) P_{li}(n_2) > 0$$
Άρα $\exists m > 0 : P_{ii}(m) > 0 \Rightarrow i \leftrightarrow i$.

(3) Με τον ίδιο τρόπο:
Αφού $i \leftrightarrow j$ και $j \leftrightarrow k$
$\exists n_1, n_2 > 0 : P_{ij}(n_1), P_{jk}(n_2) > 0$

$$P_{ik}(n_1+n_2) = \sum_{l \in S} P_{il}(n_1) P_{lk}(n_2) = P_{ij}(n_1) P_{jk}(n_2) + \sum_{l \ne j} P_{il}(n_1) P_{lk}(n_2) \ge P_{ij}(n_1) P_{jk}(n_2) > 0$$
Άρα $i \to k$. Με τον ίδιο τρόπο και η αντίστροφη πορεία.

(4) Αφού η $i \in S$ είναι βασική:
$\forall j \in S \text{ με } i \to j \Rightarrow j \to i$.
$i \leftrightarrow j$, και αποδείξαμε το πρώτο μέρος.

Για να δείξουμε ότι η $j$ είναι βασική θέλουμε $\forall k \in S \text{ με } j \to k \Rightarrow k \to j$.
Έστω, λοιπόν $j \to k$, δηλαδή $\exists m > 0 : P_{jk}(m) > 0$.
Αφού, όμως, $i \to j$ και $i$-βασική $\Rightarrow i \leftrightarrow j$.
Άρα $\exists n > 0 : P_{ij}(n) > 0$.
$$P_{ik}(n+m) = \sum_{l \in S} P_{il}(n) P_{lk}(m) = P_{ij}(n) P_{jk}(m) + \sum_{l \ne j} P_{il}(n) P_{lk}(m) > 0$$
Άρα $i \to k$.

Αφού όμως $i$-βασική $\Rightarrow k \to i$, δηλ $i \leftrightarrow k$.
Έχουμε, λοιπόν:
(a) $k \to i \Rightarrow \exists m_0 > 0 : P_{ki}(m_0) > 0$
(b) $i \leftrightarrow j \Rightarrow i \to j \Rightarrow \exists n_0 > 0 : P_{ij}(n_0) > 0$

Εύκολα, μπορούμε να δείξουμε ότι $k \to j$:
$$P_{kj}(m_0+n_0) = \sum_{l \in S} P_{kl}(m_0) P_{lj}(n_0) = P_{ki}(m_0) P_{ij}(n_0) + \sum_{l \ne i} P_{kl}(m_0) P_{lj}(n_0) > 0$$
Άρα $k \to j$ και, επομένως, $j$-βασική.


### Διαδικασία εύρεσης βασικών καταστάσεων

- Ξεκινάμε από κατάσταση $i$ και σε διάγραμμα ροής καταγράφουμε όλες τις $j \in S$ με $i \to j$.
- Συνεχίζουμε το διάγραμμα ροής από τις καταστάσεις $j \in S$ με $i \to j$, βρίσκοντας τα $k \in S$ με $j \to k$, για κάθε $j \in S$ με $i \to j$.
- Όταν έχουν εμφανιστεί όλες οι καταστάσεις σταματάμε.
- Αν υπάρχουν καταστάσεις που δεν έχουν εμφανιστεί ξεκινάμε με κάποια από αυτές νέο διάγραμμα ροής.

**Παράδειγμα**
$$\mathbb{P} = \begin{pmatrix} 0.1 & 0 & 0.9 & 0 & 0 & 0 \\ 0 & 0.6 & 0.4 & 0 & 0 & 0 \\ 0 & 0.7 & 0.3 & 0 & 0 & 0 \\ 0.8 & 0 & 0 & 0.2 & 0 & 0 \\ 0 & 0 & 0.2 & 0.4 & 0.4 & 0 \\ 0.3 & 0 & 0 & 0.4 & 0 & 0.3 \end{pmatrix}$$

(α) $1 \to 1, 1 \to 3, 3 \to 2, 3 \to 3$ (ανάλυση γραφημάτων ροής - ενδεικτικά)
(β) $2 \to 2, 2 \to 3, 3 \to 2$
(γ) $5 \to 3, 5 \to 4, 5 \to 5$
(δ) $6 \to 1, 6 \to 4, 6 \to 6$


- Από το (α) προκύπτει ότι το $\{1, 4\}$ είναι μια κλάση βασικών καταστάσεων.
- Από το (β) προκύπτει ότι το $\{2, 3\}$ είναι μια κλάση βασικών καταστάσεων.
- Από το (γ) προκύπτει ότι το $\{5\}$ είναι μια μη-βασική κατάσταση.
- Από το (δ) προκύπτει ότι το $\{6\}$ είναι μια μη-βασική κατάσταση.

### Κανονική μορφή

Η κανονική μορφή του πίνακα μετάβασης $\mathbb{P}$ κατασκευάζεται ως εξής:

- Γράφουμε πρώτα τις κλάσεις βασικών καταστάσεων με αύξουσα σειρά μεγέθους.
- Γράφουμε τις κλάσεις των μη-βασικών καταστάσεων με πρώτες εκείνες που είναι προσιτές από άλλες. Δηλαδή, δεν πρέπει να υπάρχει στον πίνακα κλάση μη-βασικών καταστάσεων που να είναι προσιτή από άλλη κλάση που βρίσκεται "ψηλότερα" στον πίνακα.

Άρα, η κανονική μορφή του παραδείγματος είναι:
$$\mathbb{P} = \begin{pmatrix} 0.1 & 0.9 & \vdots & 0 & 0 & \vdots & 0 \\ 0.8 & 0.2 & \vdots & 0 & 0 & \vdots & 0 \\ \dots & \dots & \dots & \dots & \dots & \dots & \dots \\ 0 & 0 & \vdots & 0.6 & 0.4 & \vdots & 0 \\ 0 & 0 & \vdots & 0.7 & 0.3 & \vdots & 0 \\ \dots & \dots & \dots & \dots & \dots & \dots & \dots \\ 0 & 0.4 & \vdots & 0 & 0.2 & \vdots & 0.4 & 0 \\ 0.3 & 0.4 & \vdots & 0 & 0 & \vdots & 0 & 0.3 \end{pmatrix}$$

Άρα, γενικά η κανονική μορφή $\mathbb{P}$ έχει τη μορφή:
$$\mathbb{P} = \begin{pmatrix} P_1 & 0 & \dots & 0 \\ 0 & P_2 & \dots & 0 \\ \vdots & \vdots & \ddots & \vdots \\ 0 & 0 & \dots & P_k & 0 \\ R_1 & R_2 & \dots & R_k & Q \end{pmatrix}$$
όπου:
- $P_i$ αντιστοιχούν στους πίνακες μετάβασης κάθε βασικής κλάσης.
- $R_i$ αντιστοιχούν στις μεταβάσεις από τις μη-βασικές στις βασικές κλάσεις.
- Ο πίνακας $Q$ είναι της μορφής:
$$Q = \begin{pmatrix} Q_1 & & 0 \\ & \ddots & \\ T & & Q_s \end{pmatrix}$$

Οι δυνατότητες από τη γραφή του $\mathbb{P}$ σε κανονική μορφή φαίνονται από το παρακάτω.
$$\mathbb{P}^n = \begin{pmatrix} P_1^n & 0 & \dots & 0 \\ 0 & P_2^n & \dots & 0 \\ \vdots & \vdots & \ddots & \vdots \\ 0 & 0 & \dots & P_k^n & 0 \\ R_1^{(n)} & R_2^{(n)} & \dots & R_k^{(n)} & Q^n \end{pmatrix}$$

- Η μελέτη των $R_j^{(n)}$ είναι δύσκολη και συχνά ανέφικτη.
- Για τον πίνακα $Q^n \xrightarrow{n \to \infty} 0$

**Συμπέρασμα**  
Αν ο πίνακας $\mathbb{P}$ δεν έχει μη-βασικές καταστάσεις τότε η μελέτη της ασυμπτωτικής συμπεριφοράς ανάγεται στην εύρεση του ορίου $P_1^n, \dots, P_k^n$. Άρα ανάγεται στη μελέτη ενός συνόλου ΜΑ με μόνο μία κλάση βασικών καταστάσεων.

## Αδιαχώριστες Μαρκοβιανές αλυσίδες

**Ορισμός**  
Μία ΜΑ με μία μόνο κλάση βασικών καταστάσεων και καθόλου μη-βασικές καταστάσεις ονομάζεται αδιαχώριστη ΜΑ.

$N$ μαύρες, $N$ λευκές.
$X_n := \# \text{λευκές στο (1)}$.

Βρείτε τον πίνακα μετάβασης $\mathbb{P}$ με
$P_{jk} = P(X_n=j | X_{n-1}=k)$

### Περίοδος

**Ορισμός**
Η κατάσταση $i$ έχει περίοδο $d_i$ εάν ισχύουν:
(1) $P_{ii}(n) = 0, \forall n > 0 \text{ εκτός αν } n = m \cdot d_i \text{ για } m > 0$
(2) $d_i$ είναι ο μέγιστος ακέραιος (με την (1))

- Μια κατάσταση λέγεται απεριοδική αν $d_i = 1$.

$\Rightarrow$ Εναλλακτικός ορισμός: Η περίοδος της $i \in S$ είναι ο μέγιστος κοινός διαιρέτης όλων των $n > 0$ για τους οποίους $P_{ii}(n) > 0$.

$\Rightarrow$ Εάν $i \leftrightarrow j$ τότε $d_i = d_j$.

### Κυκλικές υποκλάσεις

Έστω ΜΑ $M_t = \{X_t \in S; t \in T\}$ αδιαχώριστη με περίοδο $d$. Τότε η $M_t$ ακολουθεί την ακόλουθη κυκλική συμπεριφορά:
Έστω $i,j \in S$. Τότε, $\exists n_1, n_2, n_3 > 0$ και $n_1 < n_2$ με $P_{ij}(n_1) > 0, P_{ij}(n_2) > 0 \text{ και } P_{ji}(n_3) > 0$.

Τότε, $P_{ii}(n_1+n_3) \ge P_{ij}(n_1)P_{ji}(n_3) > 0$
$P_{ii}(n_2+n_3) \ge P_{ij}(n_2)P_{ji}(n_3) > 0$

Αφού $i,j \in S$ και $M_t$ αδιαχώριστη, $d_i=d_j=d$.
$\left. \begin{matrix} d | (n_1+n_3) \\ d | (n_2+n_3) \end{matrix} \right\} \Rightarrow d | ((n_2+n_3) - (n_1+n_3)) \Rightarrow d | (n_2 - n_1)$

Μπορούμε να γράψουμε το $n_1$ ως:
$n_1 = a \cdot d + b$, για $a, b \ge 0$ και $b \le d-1$.
Τότε, $n_2 - n_1 = c \cdot d$ για $c > 0$
Οπότε $n_2 = n_1 + cd \Rightarrow n_2 = (a+c)d + b$.

Επομένως, $n_1 \equiv n_2 \pmod d$.

Αφού $n_1, n_2$ δεν ήταν συγκεκριμένα, για οποιοδήποτε $n > 0$ με $P_{ij}(n) > 0 \Rightarrow n \equiv b \pmod d$.

Επομένως, για κάθε $i \in S$ μπορούμε να ορίσουμε την κλάση:
$$C_b(i) = \{j \in S : P_{ij}(n) > 0, \forall n \equiv b \pmod d\}$$

$$C_{b_1}(i) \cap C_{b_2}(i) = \emptyset, \quad b_1 \ne b_2$$

$\Rightarrow$ Απόδειξη:
Έστω $k \in C_{b_1}(i) \cap C_{b_2}(i)$
τότε $P_{ik}(n) > 0, \forall n \equiv b_1 \pmod d$
$P_{ik}(n) > 0, \forall n \equiv b_2 \pmod d$

Αφού $M_t$ - αδιαχώριστη και $i \to k$
έπεται ότι $\exists n_0 > 0 : P_{ki}(n_0) > 0$

Έστω, χωρίς περιορισμό της γενικότητας, ότι $b_1 < b_2$. Έστω, επίσης,
$n_1 < n_2$ με $n_1 \equiv b_1 \pmod d$
και $n_2 \equiv b_2 \pmod d$
Τότε $P_{ik}(n_1) > 0$ και $P_{ik}(n_2) > 0$

Έχουμε: $P_{ii}(n_1+n_0) \ge P_{ik}(n_1)P_{ki}(n_0) > 0$
$P_{ii}(n_2+n_0) \ge P_{ik}(n_2)P_{ki}(n_0) > 0$
Άρα $d | ((n_2+n_0) - (n_1+n_0)) \Rightarrow$
$$d | (n_2 - n_1)$$

$n_1 = c_1 d + b_1$
$n_2 = c_2 d + b_2$
$n_2 - n_1 = (c_2 - c_1)d + (b_2 - b_1)$
Άρα $d | (b_2 - b_1)$

Που σημαίνει ότι $b_1 \equiv b_2 \pmod d$
Δηλαδή $b_1 = b_2$ (αδύνατο)

Ισχύουν και οι ακόλουθες ιδιότητες:

- $\bigcup_{k=0}^{d-1} C_k(i) = S$
- Αν $C_{b_1}(i) = C_{b_2}(i) \Rightarrow b_1 \equiv b_2 \pmod d$

**Θεώρημα**  
Έστω $M_t$ - αδιαχώριστη με περίοδο $d$. Αν $i,j \in S$ και $j \in C_{b_1}(i)$, τότε $C_{b_2}(j) = C_{b_1+b_2}(i)$

**Απόδειξη**  
Έστω $k \in C_{b_2}(j) \Rightarrow P_{jk}(n) > 0, \forall n > 0 : n \equiv b_2 \pmod d$
Αφού, $j \in C_{b_1}(i) \Rightarrow P_{ij}(m) > 0, \forall m > 0 : m \equiv b_1 \pmod d$

Άρα, $P_{ik}(m+n) \ge P_{ij}(m) P_{jk}(n) > 0$
και αυτό ισχύει για όλα τα $(m+n) \equiv b_1+b_2 \pmod d$
Άρα, $C_{b_2}(j) \subseteq C_{b_1+b_2}(i)$

Ομοίως, για $C_{b_1+b_2}(i) \subseteq C_{b_2}(j)$
Επομένως, $C_{b_2}(j) = C_{b_1+b_2}(i)$

- Αυτό σημαίνει ότι μπορούμε να γράψουμε κάθε κλάση υπολοίπων μιας κατάστασης $j \in S$ ως κλάση υπολοίπων μιας οποιασδήποτε άλλης κατάστασης $i \in S$.
- Το σύνολο $C_b(i)$ δεν εξαρτάται από το $i$.
- Άρα, μπορούμε να γράφουμε, απλά $C_b$ ($0 \le b \le d-1$).
- Οι $C_b$ ονομάζονται κυκλικές υποκλάσεις (δες παρακάτω).

**Θεώρημα**  
Έστω $M_t$ - αδιαχώριστη με περίοδο $d$. Αν $i \in C_b$ και $P_{ij} > 0$, τότε $j \in C_{b+1}$.

**Απόδειξη**  
Έστω $k \in S$ με $P_{ki}(n) > 0$.
Αφού $i \in C_b \Rightarrow n \equiv b \pmod d$
$P_{kj}(n+1) \ge P_{ki}(n) P_{ij} > 0$
Αφού $n+1 \equiv b+1 \pmod d$, έπεται 
$j \in C_{b+1}$

- Η $M_t$ μεταβαίνει από $C_0 \to C_1 \to C_2 \dots \to C_{d-1}$
- Τα $C_b \ne \emptyset$, $0 \le b \le d-1$
- Ο πίνακας μετάβασης της $M_t$ μπορεί να γραφεί στη μορφή:

$$\mathbb{P} = \begin{matrix} 
 & C_0 & C_1 & C_2 & \dots & C_{d-1} \\
C_0 & 0 & P_1 & 0 & \dots & 0 \\
C_1 & 0 & 0 & P_2 & \dots & 0 \\
\vdots & \vdots & \vdots & \vdots & \ddots & \vdots \\
C_{d-2} & 0 & 0 & 0 & \dots & P_{d-1} \\
C_{d-1} & P_d & 0 & 0 & \dots & 0 
\end{matrix}$$


**Άσκηση**  

$$\mathbb{P} = \begin{pmatrix} 
0.2 & 0.5 & 0 & 0.3 & 0 & 0 & 0 \\ 
0 & 0.4 & 0 & 0 & 0 & 0 & 0.6 \\ 
0 & 0 & 0.6 & 0 & 0.4 & 0 & 0 \\ 
0 & 0 & 0 & 0.3 & 0.3 & 0.4 & 0 \\ 
0 & 0 & 0 & 0.6 & 0.1 & 0.3 & 0 \\ 
0 & 0 & 0 & 0.1 & 0.8 & 0.1 & 0 \\ 
0 & 0.8 & 0 & 0 & 0 & 0 & 0.2 
\end{pmatrix}$$

1) Να βρεθούν οι βασικές και οι μη-βασικές καταστάσεις.
2) Να γραφεί ο πίνακας στην κανονική του μορφή.

(α) (Διάγραμμα ροής 1) $\to 1, 2, 4 \to \dots \to 4, 5, 6$
(β) (Διάγραμμα ροής 3) $\to 3, 5 \to \dots$
(γ) (Διάγραμμα ροής 2) $\to 2, 7 \to \dots$

Άρα, οι $\{2,7\}$ και $\{4,5,6\}$ είναι κλάσεις βασικών. Οι $\{1\}$ και $\{3\}$ είναι μη-βασικές.

(2) $\to$ έπεται.

**Άσκηση**  
Έστω η ΜΑ με πίνακα μετάβασης:
$$\mathbb{P} = \begin{pmatrix} 
0 & 0 & 0 & 0 & 1 \\ 
0 & 0 & 1/2 & 0 & 1/2 \\ 
1/4 & 0 & 0 & 3/4 & 0 \\ 
0 & 1 & 0 & 0 & 0 \\ 
0 & 0 & 1 & 0 & 0 
\end{pmatrix}$$

Ταξινομήστε τις καταστάσεις. Αν υπάρχει περίοδος να υπολογιστεί.

**Υποδείξεις**  
$1 \to 5 \to 3 \to 1$ (και $3 \to 4$)
$4 \to 2 \to 3$ (και $2 \to 5$)

Άρα η Μ.Α. είναι αδιαχώριστη. Οι κυκλικές υποκλάσεις:
Άρα, έχουμε $C_0 = \{1, 4\}, C_1 = \{2, 5\}$ και $C_2 = \{3\}$.
Η περίοδος της αλυσίδας είναι $d=3$.

**Άσκηση**  
Δίνεται ο πίνακας μετάβασης:
$$\mathbb{P} = \begin{pmatrix} 
0.2 & p & 0 & 0.8-p \\ 
0.3 & 0.7 & 0 & 0 \\ 
0 & 0.1 & 0.1 & 0.8 \\ 
0.1 & p & 0.1 & 0.8-p 
\end{pmatrix}$$
Για ποιες τιμές του $p$ η αλυσίδα δεν είναι αδιαχώριστη;

**Λύση**  
Όταν $p = 0.8$:
(α) $\to$ κλάση $\{1, 2\}$
(β) $\to$ κλάση $\{3, 4, 1, 2\}$
Άρα διαχωρίσιμη όταν $p = 0.8$.
Όταν $p \ne 0.8$
Η Μ.Α. είναι αδιαχώριστη $\forall p \ne 0.8$.

**Άσκηση**  
Έστω ο πίνακας μετάβασης:
$$\mathbb{P} = \begin{pmatrix} 
1/2 & 1/2 & 0 & 0 & 0 & 0 \\ 
1/4 & 3/4 & 0 & 0 & 0 & 0 \\ 
1/4 & 1/4 & 1/4 & 1/4 & 0 & 0 \\ 
1/4 & 0 & 1/4 & 1/4 & 0 & 1/4 \\ 
0 & 0 & 0 & 0 & 1/2 & 1/2 \\ 
0 & 0 & 0 & 0 & 1/2 & 1/2 
\end{pmatrix}$$
- Να κατηγοριοποιήσετε τις καταστάσεις.

## Επαναληπτικές και παροδικές καταστάσεις

**Ορισμός**  

- Ορίζουμε ως χρόνο πρώτης εισόδου $\tau_j$ στην κατάσταση $j$ ως:
$$\tau_j = \min\{n \ge 1 : X(n)=j\}$$
- Ορίζουμε (ως $f_{ij}(n)$) την πιθανότητα πρώτης εισόδου της Μ.Α. στην κατάσταση $j$ ύστερα από $n$ βήματα:
$$f_{ij}(n) = \text{Prob}\{X_n=j, X_r \ne j, r=1,\dots,n-1 | X_0=i\}$$
- Τέλος, ορίζουμε ως
$$f_{ik}(n) = \text{Prob}\{X_n=k, X_r \ne k, r=1,\dots,n-1 | X_0=i\}$$

- Για να είναι πλήρεις οι παραπάνω ορισμοί ορίζουμε επίσης,
$$f_{ii}(0) = 0$$
$$f_{ij}(0) = 0$$

- Αν συμβολίσουμε με $f_i$ την πιθανότητα πρώτης επανόδου του συστήματος στην κατάσταση $i$, τότε
$$f_i = \sum_{n=1}^\infty f_{ii}(n)$$

- Ομοίως, ορίζουμε την πιθανότητα πρώτης μετάβασης από την κατάσταση $j$ στην $k$, $f_{jk}$, ως
$$f_{jk} = \sum_{n=1}^\infty f_{jk}(n)$$

**Ορισμός**  
Η κατάσταση $i$ ονομάζεται επαναληπτική αν $f_i = 1$. Αν $f_i < 1$ τότε η κατάσταση $i$ είναι παροδική.

**Παράδειγμα**  
Έστω ο πίνακας μετάβασης
$$\mathbb{P} = \begin{pmatrix} 
1/2 & 1/2 & 0 & 0 \\ 
1 & 0 & 0 & 0 \\ 
0 & 1/3 & 2/3 & 0 \\ 
1/2 & 0 & 1/2 & 0 
\end{pmatrix}$$

Αν σχεδιάσουμε την Μ.Α.
(Διάγραμμα) $1 \leftrightarrow 2$, $4 \to 1, 4 \to 3$, $3 \to 2, 3 \to 3$.

- Η $4$ είναι παροδική, αφού $f_{44}(n) = 0, \forall n \ge 0$.
- Η $3$ είναι παροδική, γιατί:
$$f_{33}(1) = \frac{2}{3}$$
$$f_{33}(n) = 0, \forall n \ge 2$$
Άρα $f_3 = \sum_{n=0}^\infty f_{33}(n) = \frac{2}{3} < 1$.

- Η $1$ είναι επαναληπτική, αφού:
$$f_1 = \sum_{n=0}^\infty f_{11}(n) = f_{11}(1) + f_{11}(2) = 1/2 + 1/2 = 1$$

- Η $2$ είναι επαναληπτική, αφού
$$f_2 = \sum_{n=0}^\infty f_{22}(n) = f_{22}(2) + f_{22}(3) + \dots + f_{22}(m) + \dots$$
$$= 0 + \frac{1}{2} + \frac{1}{4} + \frac{1}{8} + \dots$$
$$= \sum_{n=1}^\infty \frac{1}{2^n} = \frac{1/2}{1 - 1/2} = 1$$


**Ορισμός**  
Έστω $\mu_i = \sum_{n=1}^\infty n f_{ii}(n)$ ο μέσος χρόνος πρώτης επαναφοράς στην κατάσταση $i$. Τότε, αν $\mu_i < \infty$ η κατάσταση $i$ ονομάζεται θετικά επαναληπτική. Αλλιώς ($\mu_i = \infty$) ονομάζεται ασαφώς επαναληπτική.

Στο προηγούμενο παράδειγμα:

- Για την κατάσταση $1$ έχουμε:
$$\mu_1 = \sum_{n=1}^\infty n f_{11}(n) = 1 \cdot \frac{1}{2} + 2 \cdot \frac{1}{2} = \frac{3}{2}$$
Άρα η $1$ είναι θετικά επαναληπτική.
- Για την κατάσταση $2$ έχουμε:
$$\mu_2 = \sum_{n=1}^\infty n f_{22}(n) = \sum_{k=2}^\infty k \frac{1}{2^{k-1}} = 3$$
(Δε χρειάζεται. Ως άσκηση, χρειάζεται θεωρία ανελίξεων. (Προαιρετικά))

**Ορισμός**  

- Ορίζουμε την πιθανογεννήτρια συνάρτηση των πιθανοτήτων $f_{ii}(n)$ ως τη συνάρτηση:
$$F_{ii}(s) = \sum_{n=0}^\infty f_{ii}(n) s^n$$
η οποία ορίζεται πάντα για $|s| < 1$.
- Ορίζουμε την πιθανογεννήτρια των πιθανοτήτων $P_{ii}(n), n \ge 0$ ως τη συνάρτηση:
$$P_{ii}(s) = \sum_{n=0}^\infty P_{ii}(n) s^n$$

**Πρόταση**  
Ισχύει η σχέση: 
$$P_{ij}(n) = \sum_{k=0}^n f_{ij}(k) P_{jj}(n-k), \quad n \ge 1$$

**Απόδειξη**  
Αν σχεδιάσουμε τον πίνακα για τις πιθανές διαδρομές από $i \to j$:
(Πίνακας πιθανοτήτων $f_{ij}(k)$ και $P_{jj}(n-k)$ για βήματα $k=1 \dots n$)

Όλα τα πιθανά ενδεχόμενα είναι ανεξάρτητα μεταξύ τους, άρα
$$P_{ij}(n) = \sum_{k=0}^n f_{ij}(k) P_{jj}(n-k), \quad n \ge 1$$

**Πρόταση (Doeblin - χωρίς απόδειξη)**  
Έστω μία ομογενής ΜΑ $M_t = \{X_t \in S : t \in T\}$. Τότε $\forall i,j \in S$ ισχύει:
$$f_{ij} = \lim_{t \to \infty} \frac{\sum_{m=1}^t P_{ij}(m)}{1 + \sum_{n=1}^t P_{jj}(n)}$$
$\to$ Χωρίς απόδειξη

**Θεώρημα (Χωρίς απόδειξη)**  
Για οποιαδήποτε κατάσταση $i \in S$ μιας Μ.Α. έχουμε:
$$P_{ii}(s) = \frac{1}{1 - F_{ii}(s)}, \quad |s| < 1$$

**Θεώρημα (Χωρίς απόδειξη)**  
Η κατάσταση $i$ είναι επαναληπτική αν-ν 
$$\sum_{n=0}^\infty P_{ii}(n) = \infty$$

**Θεώρημα (Χωρίς απόδειξη)**  
Αν $i \leftrightarrow j$ τότε είναι του ίδιου τύπου, δηλ. και οι δύο είναι παροδικές ή ασαφώς επαναληπτικές ή θετικά επαναληπτικές και έχουν την ίδια περίοδο.

**Πρόταση (Χωρίς απόδειξη)**  
Η $i \in S$ είναι βασική αν-ν είναι επαναληπτική ή απορρόφησης. Οι μη-βασικές καταστάσεις είναι παροδικές.

## Στάσιμες κατανομες

Η μεταβατική κατανομή $\{P(n) : n \in \mathbb{N}^*\}$ είναι συνάρτηση τόσο της αρχικής κατανομής $P(0)$ όσο και της ακολουθίας πινάκων $\mathbb{P}^n$, αφού είπαμε
$$P(n) = P(0) \mathbb{P}^n$$
Άρα, η $P(n)$ εξαρτάται από το $n$.

$\hookrightarrow$ Σε συγκεκριμένες περιπτώσεις συμβαίνει η $P(n)$ να είναι σταθερή και ανεξάρτητη του $n$. Τότε, λέμε ότι η $M_t = \{X_t \in S, t \in T\}$ επιδεικνύει στάσιμη στοχαστική συμπεριφορά.

Αυτό συμβαίνει αν επιλέξουμε ως αρχική κατανομή μια στάσιμη κατανομή $\pi$, δηλ. $P(0) = \pi$, με $\pi = (\pi_i, i \in S)$ έχει την ιδιότητα:
$$\pi = \pi \mathbb{P} \quad (1)$$

Τότε $\pi \mathbb{P}^2 = (\pi \mathbb{P})\mathbb{P} = \pi \mathbb{P} = \pi$.
Και επαγωγικά
$$\pi \mathbb{P}^n = \pi$$

Έτσι, αν $P(0) = \pi$, τότε από τη σχέση
$P(n) = P(0)\mathbb{P}^n = \pi \mathbb{P}^n \Rightarrow$
$$P(n) = \pi$$

Η σχέση (1) γράφεται αναλυτικά:
$$\to \pi_j = \sum_{i \in S} \pi_i P_{ij} \quad (2)$$

Συγχρόνως, αφού $\pi$ είναι συνάρτηση πιθανότητας πρέπει να ισχύει:
$$\to \sum_{i \in S} \pi_i = 1 \quad (3)$$

Κάθε μη-αρνητική λύση του συστήματος (2), (3) αναφέρεται ως στάσιμη κατανομή της ΜΑ.
Για δεδομένη κατάσταση $j$, η (2) ονομάζεται εξίσωση ισορροπίας για την $j$. Η (3) γενικά ονομάζεται εξίσωση κανονικοποίησης.

**Παράδειγμα**  
Έστω η ΜΑ με πίνακα μετάβασης
$$\mathbb{P} = \begin{pmatrix} 1/2 & 1/4 & 1/4 \\ 2/3 & 0 & 1/3 \\ 2/3 & 1/3 & 0 \end{pmatrix}$$

Οι εξισώσεις ισορροπίας είναι:
$$(\pi_1, \pi_2, \pi_3) = (\pi_1, \pi_2, \pi_3) \begin{pmatrix} 1/2 & 1/4 & 1/4 \\ 2/3 & 0 & 1/3 \\ 2/3 & 1/3 & 0 \end{pmatrix}$$

$$\pi_1 = 1/2 \pi_1 + 2/3 \pi_2 + 2/3 \pi_3 \quad (\alpha)$$
$$\pi_2 = 1/4 \pi_1 + 1/3 \pi_3 \quad (\beta)$$
$$\pi_3 = 1/4 \pi_1 + 1/3 \pi_2 \quad (\gamma)$$

Επίσης, έχουμε ότι $\pi_1 + \pi_2 + \pi_3 = 1 \quad (\delta)$

Παραλείποντας μία από τις $(\alpha), (\beta), (\gamma)$ και συμπεριλαμβάνοντας την $(\delta)$ παίρνουμε τη μοναδική μη-αρνητική λύση.
$\pi_1 + \pi_2 + \pi_3 = 1$
$\left. \begin{matrix} \pi_2 = 1/4 \pi_1 + 1/3 \pi_3 \\ \pi_3 = 1/4 \pi_1 + 1/3 \pi_2 \end{matrix} \right\} \Rightarrow \pi_2 - \pi_3 = 1/3(\pi_3 - \pi_2)$
(Λύνουμε όλα ως προς $\pi_1$)
Βρίσκουμε $\pi = (8/14, 3/14, 3/14)$.

### Ασκήσεις

**Άσκηση**  
$$\mathbb{P} = \begin{pmatrix} 1/2 & 1/3 & 1/6 \\ 3/4 & 0 & 1/4 \\ 0 & 1 & 0 \end{pmatrix}$$
(α) Είναι αδιαχώριστη;  
(β) Αν ξεκινήσουμε από την (1) ποια η πιθανότητα να φτάσει στην (3) σε 2 βήματα;  
(γ) Περίοδος;  
(δ) Στάσιμη κατανομή;  

**Λύση**  

(α) (Διάγραμμα ροής) Όλες οι καταστάσεις επικοινωνούν. Άρα αδιαχώριστη.

(β) $$P_{13}(2) = \sum_{l=1}^3 P_{1l}P_{l3} = P_{11}P_{13} + P_{12}P_{23} = \dots = 1/6$$

(γ) Αφού είναι αδιαχώριστη, όλες οι καταστάσεις έχουν την ίδια περίοδο.
Άρα, για την (1) έχουμε
$\to$ Αν $n > 0$, άρτιος τότε επανέρχεται
$1 \to 2 \to 3 \to 2 \dots \to 1$
δηλαδή $P_{11}(n) > 0, \forall n$ άρτιο.
$\to$ Αν $n > 0$ περιττός
$1 \to 3 \to 2 \to 3 \to 2 \to 3 \dots \to 1$
δηλαδή $P_{11}(n) > 0, \forall n$ περιττό.

Άρα, $P_{11}(n) > 0, \forall n > 0$ επομένως $d=1$.
$\hookrightarrow$ Η αλυσίδα είναι απεριοδική.

(δ) $\pi \mathbb{P} = \pi \Rightarrow$
$$(\pi(1), \pi(2), \pi(3)) \begin{pmatrix} 1/2 & 1/3 & 1/6 \\ 3/4 & 0 & 1/4 \\ 0 & 1 & 0 \end{pmatrix} = (\pi(1), \pi(2), \pi(3))$$

$$\begin{cases} 1/2 \pi(1) + 3/4 \pi(2) = \pi(1) \\ 1/3 \pi(1) + \pi(3) = \pi(2) \\ 1/6 \pi(1) + 1/4 \pi(2) = \pi(3) \\ \pi(1) + \pi(2) + \pi(3) = 1 \end{cases} \Rightarrow \begin{cases} -1/2 \pi(1) + 3/4 \pi(2) = 0 \\ 1/3 \pi(1) - \pi(2) + \pi(3) = 0 \\ 1/6 \pi(1) + 1/4 \pi(2) - \pi(3) = 0 \\ \pi(1) + \pi(2) + \pi(3) = 1 \end{cases}$$

Με πράξεις γραμμών (απαλοιφή Gauss-Jornan):
$\dots$
Άρα $\pi = (1/2, 1/3, 1/6)$

**Άσκηση**  
Έχω 4 ομπρέλες. Μετακινούμαι μεταξύ γραφείου και σπιτιού. Όποτε βρέχει, παίρνω μία ομπρέλα μαζί. Αν δεν βρέχει, δεν παίρνω ομπρέλα. Ποια είναι η πιθανότητα να βραχώ, αν η πιθανότητα βροχής είναι $p$;

**Λύση**  

$X_t := \# \text{ομπρέλες στο χώρο που βρίσκομαι.}$

$q = 1-p$

Άρα, ο πίνακας μετάβασης είναι:
$$\mathbb{P} = \begin{pmatrix} 0 & 0 & 0 & 0 & 1 \\ 0 & 0 & 0 & q & p \\ 0 & 0 & q & p & 0 \\ 0 & q & p & 0 & 0 \\ q & p & 0 & 0 & 0 \end{pmatrix}$$

$\pi \mathbb{P} = \pi \Rightarrow$
$$\begin{cases} q \pi_4 = \pi_0 \\ q \pi_3 + p \pi_4 = \pi_1 \\ q \pi_2 + p \pi_3 = \pi_2 \\ q \pi_1 + p \pi_2 = \pi_3 \\ \pi_0 + p \pi_1 = \pi_4 \\ \pi_0 + \pi_1 + \dots + \pi_4 = 1 \end{cases} \Rightarrow \begin{cases} \pi_0 - q \pi_4 = 0 \\ -\pi_1 + q \pi_3 + p \pi_4 = 0 \\ q \pi_1 + p \pi_2 - \pi_3 = 0 \\ \pi_0 + p \pi_1 - \pi_4 = 0 \\ \pi_0 + \dots + \pi_4 = 1 \end{cases}$$

$$\Rightarrow \begin{cases} \pi(0) = q \pi(4) \\ \pi(1) = q \pi(3) + p \pi(4) \\ \pi(2) = \pi(3) \\ q \pi(2) + (1-p) \pi(3) = 0 \\ \pi(4) = (1-q) - p \pi(2) = 0 \end{cases} \Rightarrow \begin{cases} \pi(0) = q \pi(4) \\ \pi(1) - q \pi(3) - p \pi(4) = 0 \\ \pi(2) = \pi(3) \\ q (\pi(3) - \pi(2)) = 0 \\ p \pi(4) - p \pi(2) = 0 \end{cases}$$

$$\Rightarrow \begin{cases} \pi(0) = q \pi(4) \\ \pi(1) - q \pi(3) - p \pi(4) = 0 \\ \pi(2) = \pi(3) \\ \pi(3) = \pi(2) \\ \pi(4) = \pi(2) \end{cases} \Rightarrow \begin{cases} \pi(1) = \pi(2) = \pi(3) = \pi(4) \\ \pi(1) - q \pi(3) - p \pi(4) = 0 \end{cases}$$

Έχουμε $\sum_{i=0}^4 \pi(i) = 1 \Rightarrow \pi(0) + 4\pi(4) = 1 \Rightarrow$
$$q\pi(4) + 4\pi(4) = 1 \Rightarrow \pi(4) = \frac{1}{4+q}$$

Άρα 
$$\begin{cases} \pi(1) = \pi(2) = \pi(3) = \pi(4) = \frac{1}{4+q} \\ \pi(0) = \frac{q}{4+q} \end{cases}$$

Για παράδειγμα, αν $p=0.6$ και $q=0.4$ τότε η πιθανότητα να βραχώ είναι
$$P(\text{wet}) = \pi(0) \cdot p$$
(Πιθανότητα να είμαι σε χώρο χωρίς ομπρέλες ΚΑΙ να βρέξει).

**Bonus**:  
Αν θέλω η πιθανότητα να βραχώ να είναι κάτω από 1% πόσες ομπρέλες χρειάζομαι;
$\hookrightarrow$ Έστω ότι χρειάζομαι $N$ ομπρέλες.
Όμοια με την περίπτωση που είχα 4:
$$\pi(1) = \dots = \pi(N) = \frac{1}{q+N}$$
$$\pi(0) = \frac{q}{q+N}$$

Άρα, η πιθανότητα να βραχώ είναι
$$P(\text{wet}) = \pi(0) \cdot p = \frac{q}{q+N} \cdot p$$

Θέλω $\frac{qp}{q+N} < \frac{1}{100} \Rightarrow 100qp < q+N \Rightarrow$
$$N > 100qp - q$$

Αν πάρουμε πάλι $p=0.6$ και $q=0.4$:
$$N > 23.6$$

**Άσκηση**  
Σε έναν αυτοκινητόδρομο τα 2/3 των φορτηγών ακολουθούνται από ΙΧ. Το 1/5 των ΙΧ ακολουθούνται από φορτηγά. Ποιο το ποσοστό των ΙΧ;

**Λύση**  

Ορίζουμε $X_t = \begin{cases} 0, & \text{αν το όχημα είναι φορτηγό τη στιγμή } t \\ 1, & \text{αν το όχημα είναι ΙΧ} \end{cases}$

Είναι ΜΑ με χώρο καταστάσεων $S = \{0, 1\}$.
$$\mathbb{P} = \begin{pmatrix} 1/3 & 2/3 \\ 1/5 & 4/5 \end{pmatrix}$$

Το ποσοστό των ΙΧ αυτοκινήτων είναι το $\pi(1)$.
$$\pi \mathbb{P} = \pi \Rightarrow (\pi(0), \pi(1)) \begin{pmatrix} 1/3 & 2/3 \\ 1/5 & 4/5 \end{pmatrix} = (\pi(0), \pi(1))$$

$$\Rightarrow \begin{cases} 1/3 \pi(0) + 1/5 \pi(1) = \pi(0) \\ 2/3 \pi(0) + 4/5 \pi(1) = \pi(1) \\ \pi(0) + \pi(1) = 1 \end{cases} \Rightarrow \dots \Rightarrow \begin{cases} \pi(1) = \frac{10}{13} \\ \pi(0) = \frac{3}{13} \end{cases}$$

Άρα, περίπου 76% είναι ΙΧ.
